# Generated by Gemini Code Assist

from django.db import migrations
from django.utils import timezone
from django.contrib.auth.hashers import make_password
import datetime
import random


def seed_data(apps, schema_editor):
    """
    Seeds the database with sample data for analytics.
    """
    User = apps.get_model('api', 'User')
    ParkingLot = apps.get_model('api', 'ParkingLot')
    ParkingSlot = apps.get_model('api', 'ParkingSlot')
    Booking = apps.get_model('api', 'Booking')
    Payment = apps.get_model('api', 'Payment')
    Review = apps.get_model('api', 'Review')
    AuditLog = apps.get_model('api', 'AuditLog')

    # --- 1. Ensure Base Users and Lots Exist ---
    
    # Get or create a manager
    manager, _ = User.objects.update_or_create(
        email='analytics.manager@demo.com',
        defaults={
            'username': 'Analytics Manager',
            'password': make_password('password123'),
            'role': 'manager',
            'is_staff': False,
            'is_superuser': False,
        }
    )

    # Get or create drivers
    drivers = []
    for i in range(1, 6):
        driver, _ = User.objects.update_or_create(
            email=f'driver{i}@analytics.com',
            defaults={
                'username': f'Analytics Driver {i}',
                'password': make_password('password123'),
                'role': 'driver',
            }
        )
        drivers.append(driver)

    # Get or create a parking lot
    lot, _ = ParkingLot.objects.update_or_create(
        name='Analytics Test Lot',
        defaults={
            'location': 'Data City',
            'manager': manager,
            'total_capacity': 50,
            'hourly_rate': 75.00,
        }
    )

    # Get or create parking slots
    available_slots = list(ParkingSlot.objects.filter(parking_lot=lot))
    if len(available_slots) < 20:
        for i in range(len(available_slots), 50):
            slot, _ = ParkingSlot.objects.update_or_create(
                parking_lot=lot,
                slot_number=f'S{i+1}',
                defaults={'status': 'available'}
            )
            available_slots.append(slot)

    # --- 2. Create Bookings and Payments (Last 30 days) ---
    
    bookings_to_create = []
    payments_to_create = []
    for i in range(30):
        random_day = timezone.now() - datetime.timedelta(days=random.randint(0, 29), hours=random.randint(1, 12))
        duration = random.randint(1, 5)
        
        booking = Booking(
            user=random.choice(drivers),
            parking_slot=random.choice(available_slots),
            start_time=random_day,
            end_time=random_day + datetime.timedelta(hours=duration),
            duration_hours=duration,
            vehicle_number=f"KDA {random.randint(100,999)}X",
            hourly_rate=lot.hourly_rate,
            total_amount=duration * lot.hourly_rate,
            booking_reference=f"BK-ANL-{random.randint(10000, 99999)}",
            status='completed',
            created_at=random_day,
            updated_at=random_day
        )
        bookings_to_create.append(booking)

    # Bulk create bookings. Note: On some DBs like MySQL, bulk_create doesn't return PKs.
    Booking.objects.bulk_create(bookings_to_create)

    # To work around the missing PKs, we retrieve the bookings we just created
    # using a unique field we know, like the booking_reference.
    booking_references = [b.booking_reference for b in bookings_to_create]
    created_bookings_from_db = Booking.objects.filter(booking_reference__in=booking_references)

    # Create payments for each booking
    for booking in created_bookings_from_db:
        payment = Payment(
            booking=booking,
            amount=booking.total_amount,
            payment_method=random.choice(['mpesa', 'card']),
            status='completed',
            transaction_id=f"TR-ANL-{random.randint(10000, 99999)}",
            created_at=booking.created_at,
            updated_at=booking.created_at
        )
        payments_to_create.append(payment)

    Payment.objects.bulk_create(payments_to_create)

    # --- 3. Create Reviews ---
    
    reviews_to_create = []
    used_drivers = []
    for i in range(12):
        driver = random.choice(drivers)
        if driver in used_drivers: continue # Avoid duplicate user-lot review
        
        review = Review(
            user=driver,
            parking_lot=lot,
            rating=random.randint(3, 5),
            comment=f"This is a sample review number {i+1}. The experience was great.",
            created_at=timezone.now() - datetime.timedelta(days=random.randint(0, 20))
        )
        reviews_to_create.append(review)
        used_drivers.append(driver)
    Review.objects.bulk_create(reviews_to_create)

    # --- 4. Create Audit Logs ---
    
    audit_logs_to_create = []
    actions = ['USER_LOGIN', 'BOOKING_CREATED', 'PAYMENT_SUCCESS', 'PROFILE_UPDATED']
    for i in range(20):
        log = AuditLog(
            user=random.choice(drivers),
            action=random.choice(actions),
            entity_type='Booking',
            entity_id=random.randint(1, 30),
            created_at=timezone.now() - datetime.timedelta(minutes=random.randint(1, 500))
        )
        audit_logs_to_create.append(log)
    AuditLog.objects.bulk_create(audit_logs_to_create)


def unseed_data(apps, schema_editor):
    """
    Removes the seeded data. This is a destructive operation for development.
    """
    Booking = apps.get_model('api', 'Booking')
    Booking.objects.filter(booking_reference__startswith='BK-ANL-').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, unseed_data),
    ]